### ISSUE TITLE
packet_ip_attachment: Facility can't be blank 

### ISSUE THREAD

**Issue by epiloque** [terraform-providers/terraform-provider-packet#33]
The terraform configuration is [here](https://github.com/epiloque/stack/blob/e239f3ab5199ff9680645c8d346cd5d512dde8c1/terraform/packet/device/main.tf) and [here](https://github.com/epiloque/stack/blob/e239f3ab5199ff9680645c8d346cd5d512dde8c1/terraform/packet/device.test/main.tf). The full debug log is [here](https://travis-ci.org/epiloque/stack/jobs/289212276#L841-L851).

Thank you!

```
Error applying plan:
2 error(s) occurred:
* module.packer_device.packet_ip_attachment.attachment[1]: 1 error(s) occurred:
* packet_ip_attachment.attachment.1: error assigning address 147.75.68.6/32} to device b183b628-dabe-4f7c-91a8-e5743f68cd6c: POST https://api.packet.net/devices/b183b628-dabe-4f7c-91a8-e5743f68cd6c/ips: 422 Facility can't be blank 
* module.packer_device.packet_ip_attachment.attachment[0]: 1 error(s) occurred:
* packet_ip_attachment.attachment.0: error assigning address 147.75.80.230/32} to device 6adea1a3-dc01-4e86-9c6d-b9a8354e0b16: POST https://api.packet.net/devices/6adea1a3-dc01-4e86-9c6d-b9a8354e0b16/ips: 422 Facility can't be blank 
```

### Versions

- Terraform v0.10.6
- Packer provider 1.1.0

### Affected Resource(s)

- `packet_ip_attachment`

### Steps to Reproduce

```sh
git clone --recursive https://github.com/epiloque/stack.git
cd stack
git checkout e239f3ab5199ff9680645c8d346cd5d512dde8c1
./manage download-terraform
export TF_VAR_PACKET_PROJECT_ID=
export PACKET_AUTH_TOKEN=
./manage test-terraform packet/device
```

**Comment by t0mk** [comment]
hi @epiloque, thanks for the report. I will take a look on this today in the afternoon.

**Comment by t0mk** [comment]
Hi again @epiloque, you have very nice infrastructure repo and tooling :eyes:, I will go back to your "manage" once I will need to do heavy shell scripting (hopefully not anytime soon though).

The error is caused by a curly brace in the end of the "cidr_notation" param in the assignment resource:
https://travis-ci.org/epiloque/stack/jobs/289212276#L816

It's coming from:
https://github.com/epiloque/stack/blob/e239f3ab5199ff9680645c8d346cd5d512dde8c1/terraform/packet/device/main.tf#L67

The error message from the API is obviously misleading, and I will report it to Packet people <= thanks for pointing it out!

**Comment by epiloque** [comment]
Oh! Thank you @t0mk for solving this for me! (there is no getting away from bash scripts :laughing:)
