### ISSUE TITLE
IPv6 /64 assignment

### ISSUE THREAD

**Issue by l5x** [terraform-providers/terraform-provider-packet#36]
Hello,

This is not an issue, just wanted to ask if there is a way to assign a IPv6 /64 block from the packet.net projects /56 network. I'm seeing `address_family` in the `packet_ip_attachment` attributes - is it intended for this use?

Thank you!

**Comment by t0mk** [comment]
Hi @epiloque 
theoretically, you can assign subnet from any (6 or 4) block in your project to a device in your projects, provided that the block and device are in the same facitliy.

Same goes for the pre-created /56 blocks. E.g., if you have device in your project, you can find out the available /64 subnets (through the UI or API), and then you can just attach it:

```hcl
resource "packet_ip_attachment" "from_ipv6_block" {
    device_id = "b8543291-08f3-45ac-b1cb-5381be5a0621"
    cidr_notation = "2604:1380:0004:0203::/64"
}
```

I guess that example is not very helpful for you, and indeed, the problem is getting the reference of the pre-created blocks to Terraform. TF is good at managing resources which is has created, but not (yet) very good in importing existing resources (but [getting there](https://www.terraform.io/docs/import/index.html)).

I tried the import on IPv6 block and run in some problems - I will fix it and get back to you.

**Comment by epiloque** [comment]
Thank you for your time @t0mk. I'm thinking that maybe a terraform data source would be a good fir for fetching the pre-created /56 blocks.

**Comment by t0mk** [comment]
@epiloque Yes, I guess too. I look at it, because it seems like an important feature to be able to assign the public IPv6 subnets from Terraform.

**Comment by epiloque** [comment]
Thank you very much @t0mk.

**Comment by t0mk** [comment]
Hi @epiloque,
PR #37 should fix this issue. Check the docfile in the PR.
