### ISSUE TITLE
Wrong number of resources to be applied in plan

### ISSUE THREAD

**Issue by pgporada** [terraform-providers/terraform-provider-packet#4]
### Terraform Version
0.9.11

### Affected Resource(s)
packet_ssh_key

### Debug Output
https://gist.github.com/pgporada/cbf8bab9411c3612fe273fdde2e9206f

### Expected Behavior
When adding a resource, the correct # of resources to be added is displayed

### Actual Behavior
The terraform plan said 2 resources would be added, but only 1 was added. The plan math seems to be wrong.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by radeksimko** [comment]
Hi @pgporada 
do you mind sharing config files (minus secrets) which would help us reproduce (and fix) this misbehaviour?

Thanks.

**Comment by pgporada** [comment]
@radeksimko Sure thing, here's the code I wrote https://github.com/pgporada/terraform-packetdotnet

**Comment by pgporada** [comment]
I am still encountering this with Terraform 0.11.2 and Packet.net provider v1.2.

**Comment by pgporada** [comment]
This might be due to the provider itself. If a project id is not specified then a new project is created inside the Packet web UI. The packet_ssh_key resource does not require a project id and I'm wondering if the provider doesn't check to see if a project of the same name exists.

**Comment by t0mk** [comment]
@pgporada I tried with your conf, I was not able to reproduce. TF v0.11.2, and newest provider.

In order to have TF consider resources, which were not created by it, you'd need to import them to current state before `tf apply`. 
https://www.terraform.io/docs/import/usage.html

.. otherwise TF will not consider them. Also, you can't specify ID in resource declaration, ID is implicit `computed` parameter.

**Comment by pgporada** [comment]
We stopped using Terraform so I'm unsure if it's still a problem.
