### ISSUE TITLE
Support for Layer2 networks

### ISSUE THREAD

**Issue by atosatto** [terraform-providers/terraform-provider-packet#54]
Hi there,

I am using Terraform and Packer to automate the creation of VMWare clusters.
For this specific purpose, it would be great to have in the Packer provider support for Layer2 networks.

Thanks.

**Comment by vielmetti** [comment]
My assumption is that being able to exercise this set of functions

https://help.packet.net/technical/networking/layer-2-configurations

from Terraform is the goal.

**Comment by t0mk** [comment]
the new link for L2 configuration:
https://packet.kayako.com/article/58-layer-2-configurations

**Comment by jacobsmith928** [comment]
Updated doc url:
https://support.packet.com/kb/articles/layer-2-overview

**Comment by shanedizer** [comment]
we also have heavy automation around our packet infrastructure, and this would greatly deployments of our openstack infra..

**Comment by t0mk** [comment]
This will be fixed by #86.

I still need to figure the covert to  the pure L2 mode, the last (3rd) use case from 
https://support.packet.com/kb/articles/layer-2-configurations

I will make it a priority. Hopefully this comes soon.

Also, if you want to give early feedback, check the example L2 templates in
https://github.com/t0mk/packet-l2-terraform

**Comment by t0mk** [comment]
this was fixed by #86
