### ISSUE TITLE
Improved error messages 

### ISSUE THREAD

**Issue by vielmetti** [terraform-providers/terraform-provider-packet#66]
I'm trying to sort out what is going on with the CNCF cross-cloud CI system for Kubernetes, which uses Terraform to set up resources. (http://cncf.ci) As a piece of that I'm looking through logs and come up blank because some of the error messages are not as good as they might be.  See e.g. from https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/81265

```
Error: Error applying plan:

2 error(s) occurred:
* module.master.packet_device.masters[1]: 1 error(s) occurred:
* packet_device.masters.1: 
* module.master.packet_device.masters[0]: 1 error(s) occurred:
* packet_device.masters.0: 
```

**Comment by vielmetti** [comment]
Bringing this to the attention of @t0mk - the question I have is whether the Packet API is correctly throwing an error or not, or if Terraform is silently discarding it.

**Comment by t0mk** [comment]
you cna try to set TF_LOG=DEBUG env var for the terraform runs (especially for `terraform apply`) to see more of what's going on.

Or you could investigate from the Packet API side, and see what's happens there on the tf run.

Otherwise, it's impossible to say what's going on without the HCL files - that's why they are mentioned in the Issue Template for every TF provider.

**Comment by vielmetti** [comment]
Thanks @t0mk . All of the provisioning parts for this system are in the https://github.com/crosscloudci/cross-cloud repo, especially https://github.com/crosscloudci/cross-cloud/tree/master/packet

**Comment by t0mk** [comment]
@BRMatt thanks, for the submission.

I just tried to create device with underscore in the name, so that I get API error, and the `terraform apply` will show:

```
Error: Error applying plan:

1 error(s) occurred:

* packet_device.web1: 1 error(s) occurred:

* packet_device.web1: Hostname is not a valid hostname (can only contain alphanumeric values, dashes, and periods)
```

Do you have any idea what the error could be, so that I can replicate and debug this? I don't suggest you use TF_LOG=DEBUG all the time, maybe just once, to see what is causing the mute message.

**Comment by jasmingacic** [comment]
@vielmetti This one is really hard to replicated. I noticed that the code is capturing all possible errors that might come from the API. So I believe that in some occasions API doesn't return any error messages.

Should we close this one?

**Comment by vielmetti** [comment]
Hi @jasmingacic - I'm OK with closing this out for now, with the notation that if the problem reappears we'll aim to chase it from the Packet API side and not the Terraform side.
